# Data loading & Pre-Processing

In [1]:
import pandas as pd
import dask.dataframe as dd
import os
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

In [2]:
#Setting current directory

os.chdir("..")

In [3]:
#Setting directory for input & output files

path=os.getcwd()
input_files = path+'/Input_files/'
output_files = path+'/Output/'

Column legends

D_* = Delinquency variables
S_* = Spend variables
P_* = Payment variables
B_* = Balance variables
R_* = Risk variables

In [4]:
amex_tx_data = dd.read_csv(input_files+'train_data.csv')

In [5]:
%%time

amex_tx_data = amex_tx_data.compute()

Wall time: 1min 12s

In [6]:
op_labels = dd.read_csv(input_files+'train_labels.csv',assume_missing=True)

In [7]:
%%time
op_labels = op_labels.compute()

Wall time: 533 ms

In [8]:
print(amex_tx_data.shape)
amex_tx_data = amex_tx_data.merge(op_labels, how='left', on='customer_ID')
print(amex_tx_data.shape)

(5531451, 190)
(5531451, 191)

In [9]:
data_amx = amex_tx_data.copy()

In [10]:
%%time
data_amx['target'].value_counts() #checking if dataset is balanced or not

Wall time: 72.3 ms

0.0    4153582
1.0    1377869
Name: target, dtype: int64

In [11]:
data_amx1 = data_amx.groupby('customer_ID')#grouped on 'customer id'

In [12]:
%%time

data_amx2 = data_amx1.tail(1) #selected latest transaction records

Wall time: 2.44 s

In [13]:
data_amx2.drop(columns=['S_2'],inplace=True)
data_amx2

C:\Users\akshay.masurkar\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,customer_ID,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,...,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
12,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.934745,0.009119,0.009382,1.007647,0.006104,0.135021,0.001604,0.007174,NaN,...,NaN,NaN,0.007186,0.004234,0.005086,NaN,0.005810,0.002970,0.008533,0.0
25,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.880519,0.178126,0.034684,1.004028,0.006911,0.165509,0.005552,0.005068,NaN,...,NaN,NaN,0.002980,0.007479,0.007870,NaN,0.003284,0.003169,0.008514,0.0
38,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.880875,0.009704,0.004284,0.812650,0.006450,NaN,0.003796,0.007196,NaN,...,NaN,NaN,0.007383,0.006623,0.000964,NaN,0.002202,0.000834,0.003444,0.0
51,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.621776,0.001083,0.012564,1.006183,0.007829,0.287766,0.004532,0.009937,NaN,...,NaN,NaN,0.002704,0.006184,0.001899,NaN,0.008183,0.005560,0.002983,0.0
64,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.871900,0.005573,0.007679,0.815746,0.001247,NaN,0.000231,0.005528,NaN,...,NaN,NaN,0.002974,0.004162,0.005764,NaN,0.008154,0.006944,0.000905,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531398,ffff41c8a52833b56430603969b9ca48d208e7c192c6a4...,0.844229,0.447585,0.028515,1.009867,0.001928,0.128707,0.003482,0.005893,NaN,...,NaN,NaN,0.007917,0.001520,0.005530,NaN,0.001430,0.003009,0.004843,0.0
5531411,ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fd...,0.831279,0.033670,0.292360,0.055656,0.006953,NaN,0.005791,0.233078,NaN,...,NaN,NaN,0.004393,0.006185,0.001480,NaN,0.004794,0.009230,0.006435,0.0
5531424,ffff9984b999fccb2b6127635ed0736dda94e544e67e02...,0.800522,0.267018,0.020563,1.007023,0.000957,0.066648,0.007424,0.006314,NaN,...,NaN,NaN,0.006035,0.002869,0.002149,NaN,0.008031,0.000340,0.002148,0.0
5531437,ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf38814...,0.754129,0.008619,0.015838,0.714486,0.000993,0.408849,0.003392,0.050048,NaN,...,NaN,NaN,1.009894,0.004478,0.949723,0.446255,1.009310,0.002502,0.185527,1.0
5531450,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,0.982175,0.002474,0.000077,0.992880,0.000809,0.119165,0.003287,0.014092,NaN,...,NaN,NaN,0.007316,0.002888,0.006207,NaN,0.005110,0.003184,0.001914,0.0

In [14]:
data_amx2['target'].value_counts()

0.0    340085
1.0    118828
Name: target, dtype: int64

In [15]:
data_amx2.describe()

,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,...,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
count,455944.000000,4.589130e+05,458913.000000,4.588820e+05,4.589130e+05,373943.000000,4.588820e+05,4.588820e+05,59910.000000,324591.000000,...,1.639500e+04,1.639500e+04,4.560830e+05,4.589130e+05,4.560830e+05,80315.000000,4.560830e+05,4.589130e+05,4.560830e+05,458913.000000
mean,0.635249,2.014895e-01,0.139027,5.916128e-01,1.073958e-01,0.229064,9.948801e-02,1.548291e-01,0.177988,0.163768,...,1.414993e-02,1.590173e-01,1.811025e-01,2.893126e-02,1.665783e-01,0.394761,1.809953e-01,5.201583e-02,6.379602e-02,0.258934
std,0.267547,4.021565e-01,0.231266,4.121456e-01,2.786386e-01,0.198845,3.040705e-01,2.550615e-01,0.253631,0.227059,...,9.529647e-02,2.610814e-01,3.809093e-01,1.528808e-01,3.501717e-01,0.241254,3.808317e-01,1.820323e-01,1.970930e-01,0.438050
min,-0.458955,7.406592e-08,-3.571172,2.024839e-07,5.646122e-08,-0.508883,3.998730e-08,7.574315e-08,-0.000240,0.000002,...,3.704722e-07,1.703873e-07,2.207831e-08,7.897955e-09,9.490087e-08,-0.011438,1.653580e-08,1.995319e-08,2.811854e-09,0.000000
25%,0.449332,4.782223e-03,0.008984,7.091162e-02,2.957326e-03,0.127512,3.008724e-03,5.483745e-03,0.031770,0.043333,...,2.518881e-03,3.482435e-03,3.045516e-03,2.551175e-03,3.027869e-03,0.200727,3.032092e-03,2.757897e-03,3.031604e-03,0.000000
50%,0.682559,9.559730e-03,0.033219,8.134054e-01,5.920879e-03,0.164910,6.010615e-03,1.082996e-02,0.108293,0.092436,...,5.052533e-03,7.028427e-03,6.078699e-03,5.120597e-03,6.050620e-03,0.386107,6.065281e-03,5.501409e-03,6.072661e-03,0.000000
75%,0.862186,2.665587e-01,0.153634,1.001955e+00,8.891468e-03,0.264784,8.998209e-03,2.106605e-01,0.230394,0.195026,...,7.578314e-03,5.013750e-01,9.101306e-03,7.674505e-03,9.101263e-03,0.573958,9.097647e-03,8.251762e-03,9.101820e-03,1.000000
max,1.009998,5.001550e+00,1.324059,1.010000e+00,2.759738e+00,3.993525,8.988807e+00,1.596532e+00,4.186138,9.185313,...,1.009950e+00,2.505057e+00,1.010000e+00,1.010000e+00,1.339910e+00,2.229182,1.010000e+00,1.343326e+00,4.827630e+00,1.000000

# Encoding features

There is ordered categorical data in columns 'D_63' & 'D_64', so we will encode those columns using ordinal encoding

Ordered categorical means it will indicate range or intensity.

for ex: low, medium, high

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
oe = OrdinalEncoder()

In [18]:
data_amx2['D_63'] = oe.fit_transform(data_amx2[['D_63']])
data_amx2['D_64'] = oe.fit_transform(data_amx2[['D_64']])

C:\Users\AKSHAY~1.MAS\AppData\Local\Temp/ipykernel_24416/1532070317.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_amx2['D_63'] = oe.fit_transform(data_amx2[['D_63']])
C:\Users\AKSHAY~1.MAS\AppData\Local\Temp/ipykernel_24416/1532070317.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_amx2['D_64'] = oe.fit_transform(data_amx2[['D_64']])

In [19]:
data_amx2.fillna(0,inplace=True)

C:\Users\akshay.masurkar\Anaconda3\lib\site-packages\pandas\core\frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [20]:
x = data_amx2.iloc[:,1:-1]
y = data_amx2.iloc[:,-1]

In [21]:
from imblearn.over_sampling import SMOTE
# Resampling the minority class. The strategy can be changed as required.
sm = SMOTE(sampling_strategy='minority', random_state=42)

In [22]:
x_s, y_s = sm.fit_resample(x,y)

# Feature selection

In [23]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [24]:
data_amx2.corr()

,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,...,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,target
P_2,1.000000,-0.320130,-0.388025,0.580938,-0.540703,-0.357828,-0.408814,-0.479612,-0.236477,-0.295661,...,-0.021299,-0.084787,-0.173669,-0.144354,-0.169162,-0.120323,-0.173663,0.012482,-0.156253,-0.650629
D_39,-0.320130,1.000000,0.244894,-0.290274,0.387424,0.172050,0.645252,0.228652,0.040397,0.092417,...,-0.000154,0.017357,0.042189,0.040158,0.041735,0.033520,0.042108,0.003377,0.033202,0.339477
B_1,-0.388025,0.244894,1.000000,-0.627157,0.280121,0.226147,0.272799,0.735572,0.006768,0.091581,...,0.007107,0.031944,0.106219,0.061251,0.105349,0.088814,0.106192,0.034230,0.082027,0.449427
B_2,0.580938,-0.290274,-0.627157,1.000000,-0.369735,-0.290025,-0.333386,-0.720524,-0.083869,-0.177880,...,-0.012542,-0.051438,-0.160033,-0.106454,-0.158013,-0.127438,-0.160047,-0.035498,-0.129659,-0.557633
R_1,-0.540703,0.387424,0.280121,-0.369735,1.000000,0.251246,0.425341,0.320437,0.103708,0.222118,...,0.009435,0.060304,0.088407,0.082526,0.087173,0.071696,0.088403,0.001547,0.078900,0.473530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D_142,-0.120323,0.033520,0.088814,-0.127438,0.071696,0.039810,0.050947,0.121294,0.012024,0.058397,...,0.004589,0.005802,0.829655,0.263406,0.854476,1.000000,0.829315,0.654572,0.597269,0.092518
D_143,-0.173663,0.042108,0.106192,-0.160047,0.088403,0.070027,0.064292,0.144422,0.035491,0.086656,...,0.006156,0.009303,0.999603,0.339591,0.997742,0.829315,1.000000,0.559980,0.645606,0.129040
D_144,0.012482,0.003377,0.034230,-0.035498,0.001547,-0.010000,0.007385,0.040526,-0.020946,0.003542,...,-0.001564,-0.007410,0.560756,-0.040425,0.587076,0.654572,0.559980,1.000000,0.209036,-0.004368
D_145,-0.156253,0.033202,0.082027,-0.129659,0.078900,0.062318,0.055465,0.116600,0.036451,0.073203,...,0.005278,0.008804,0.645552,0.222570,0.631991,0.597269,0.645606,0.209036,1.000000,0.116829
target,-0.650629,0.339477,0.449427,-0.557633,0.473530,0.360162,0.377547,0.506814,0.199879,0.294554,...,0.020918,0.083631,0.129028,0.127404,0.126066,0.092518,0.129040,-0.004368,0.116829,1.000000

In [25]:
test_df=pd.DataFrame(columns=['Col_Name','f_Value'])
test_df['Col_Name'] = x_s.columns
test_df['f_Value']= f_classif(x_s,y_s)[0]
test_df

    Col_Name        f_Value
0        P_2  649933.226722
1       D_39   69234.188399
2        B_1  171029.831574
3        B_2  433981.538156
4        R_1  138113.931268
..       ...            ...
183    D_141   10846.746412
184    D_142    5256.685971
185    D_143   11416.267995
186    D_144     163.884647
187    D_145    8716.665859

[188 rows x 2 columns]

In [26]:
feature_rank = SelectKBest(score_func=f_classif, k=5)
ordered_features = feature_rank.fit(x_s,y_s)

In [27]:
ordered_features.get_feature_names_out()

array(['P_2', 'B_2', 'D_48', 'D_61', 'B_18'], dtype=object)

In [28]:
x_s = x_s[ordered_features.get_feature_names_out()]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x_s,y_s,test_size=0.3,random_state=0)

# ANN

In [31]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
import keras_tuner as kt
from tensorflow.keras import layers

In [35]:
def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Flatten())
    # Tune the number of layers.
    for i in range(hp.Int("num_layers", 5, 21)):
        model.add(
            layers.Dense(
                # Tune number of units separately.
                units=hp.Int(f"units_{i}", min_value=32, max_value=512, step=32),
                activation=hp.Choice("activation", ["relu", "tanh"]),
            )
        )
    model.add(layers.Dense(1, activation="sigmoid"))
    model.compile(
        optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',[1e-2,1e-3,1e-4])),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return model

In [36]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5)

INFO:tensorflow:Reloading Oracle from existing project .\untitled_project\oracle.json
INFO:tensorflow:Reloading Tuner from .\untitled_project\tuner0.json

In [37]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))
best_model = tuner.get_best_models()[0]

Trial 5 Complete [00h 10m 47s]
val_accuracy: 0.8713262677192688

Best val_accuracy So Far: 0.8713262677192688
Total elapsed time: 00h 21m 24s
INFO:tensorflow:Oracle triggered exit

In [39]:
best_model.evaluate(x_test, y_test)

6377/6377 [==============================] - 12s 2ms/step - loss: 0.3086 - accuracy: 0.8713

[0.3086293637752533, 0.8713262677192688]